name: CI

on:
  push:
    paths:
      - 'docs/**' # Déclencher seulement si des changements sont faits dans le répertoire "docs"
      - '.github/workflows/ci.yml' # Déclencher seulement si des changements sont faits dans le fichier de workflow

jobs:
  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'flecourtier/PHDResults' &&
      !startsWith(github.event.head_commit.message, 'Release ') &&
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
    - run: echo ok go

  build_antora:
    needs: [activate]
    runs-on: ubuntu-latest
    name: Build, Install, Package documentation
    if: "!contains(github.event.head_commit.message, 'docs skip')"
    steps:
    - uses: actions/checkout@v3
    - name: Install credentials
      run: echo https://$GITHUB_OAUTH:@github.com > $HOME/.git-credentials
      env:
        GITHUB_OAUTH: ${{ secrets.DOCS_GITHUB_KEY }}
    - name : Remove previous Deploy
      run: |
        rm -rf public
      working-directory: docs/antora
    - name: Build
      run: |
        python3 -m pip install --upgrade pip
        npm install --no-audit --no-fund
        npm run antora
      working-directory: docs/antora
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/antora/public # The folder the action should deploy.